---
dmarc_metrics_exporter_version: ""
dmarc_metrics_exporter_virtualenv_path: /opt/dmarc-metrics-exporter

listen_addr: "127.0.0.1"
listen_port: 9797

imap_host: "localhost"
imap_port: 993
poll_interval_seconds: 60
deduplication_max_seconds: 604800

folder_inbox: "INBOX"
folder_done: "Archive"
folder_error: "Invalid"
